# Generated by Django 6.1 on 2026-09-02 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='application',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(choices=[('PG', 'Post Graduate'), ('UG', 'Under Graduate'), ('+2', '+2'), ('10', '10th')], max_length=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('qualification', 'Highest Qualification Certificate'), ('aadhaar', 'Aadhaar'), ('photo', 'Photo'), ('signature', 'Signature')], max_length=30)),
                ('file', models.FileField(upload_to='admissions/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'document_type'), name='unique_application_document_type')],
            },
        ),
    ]
