# Generated by Django 6.1 on 2026-09-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_application_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='highest_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.educationalqualification'),
        ),
    ]
