# Generated by Django 6.1 on 2026-09-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_educationalqualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='highest_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.educationalqualification'),
        ),
    ]
