# Generated by Django 6.1 on 2026-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_application_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='access_token_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
